[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# --clean-alluredir автоматически сносит старые отчеты и видео перед новым запуском
addopts = -v -s --tb=short --alluredir=allure-results --clean-alluredir